version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  postgres:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: gestao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --requirepass password --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.data/duducp/Redis:/var/lib/postgresql/data

  mysql:

