version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  postgres:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: gestao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - banco-dados

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.data/duducp/RedisData:/data # Montando o diretório de dados do Redis
    networks:
      - banco-dados

  gerenciador:
    image: gacacio/gerenciador:1.0.0
    ports:
      - "8080:8080"
    environment:
      PORT: 6379
      HOST: redis
      POSTGRES: jdbc:postgresql://postgres:5432/gestao
      USERNAME: postgres
      PASSWORD: 1234567
    networks:
      - banco-dados
    depends_on:
      - postgres
      - redis

networks:
  banco-dados:
    driver: bridge

